export type Enviroment = {
	readonly API_PORT?: number;
	readonly API_VERSION?: string;
	readonly ENABLE_SWAGGER?: boolean;
	readonly DB_HOST?: string;
	readonly DB_PORT?: number;
	readonly DB_USER?: string;
	readonly DB_PASSWORD?: string;
	readonly DB_NAME?: string;
	readonly DB_SYNC?: boolean;
	readonly DB_LOG?: boolean;
	readonly JWT_SECRET_KEY?: string;
	readonly AWS_ACCESS_KEY?: string;
	readonly AWS_SECRET_ACCESS_KEY?: string;
	readonly AWS_S3_BUCKET?: string;
	readonly JWT_EXPIRES_IN?: string;
	readonly JOB_RETRY_COUNT?: number;
	readonly MAX_RUNNING_JOBS?: number;
	readonly JOB_TIMEOUT?: number;
	readonly CELL_COUNTER_URL?: string;
	readonly CELL_COUNTER_TIMEOUT?: number;
};
