export const DI_ENVIRONMENT = "ENVIRONMENT";
export const DI_AUTHSERVICE = "AUTHSERVICE";
export const DI_JWTSTRATEGY = "JWTSTRATEGY";
export const DI_DOCUMENTSERVICE = "DOCUMENTSERVICE";
export const DI_HEMOGRAMEXAMSERVICE = "HEMOGRAMEXAMSERVICE";
export const DI_JOBSERVICE = "JOBSERVICE";
export const DI_USERENTITYSUBSCRIBER = "USERENTITYSUBSCRIBER";
export const DI_USERSERVICE = "USERSERVICE";
